### ISSUE TITLE
Vignetting calibration with LCD instead of paper

### ISSUE THREAD

**Issue by caselitz** [taketwo/radical#3]
Hi,

if I understand correctly, the critical assumption for vignetting calibration is that the white sheet of paper has uniform white color and is uniformly illuminated. While the first one might be sufficiently given for a normal sheet of paper, I think the second one is quite hard to achieve.

[Here](http://www.imatest.com/docs/uniformity_int/) the following method is proposed:

> One of the simplest ways to obtain a uniform subject is to photograph your computer monitor at a distance of 1-3 inches (2-8 cm)

I tried it with an Xtion Pro Live. The room was completely dark except for the monitor and I moved the camera in front of the screen to average out potential inhomogeneity in screen illumination.

The results looked reasonable (radial symmetric) but now I realized that the calibration is overcompensating in the outer parts of the image. But I've to perform more experiments...

I wanted to ask what you think about this way, if you've tried it, and how your results are.

Best,
Tim

**Comment by taketwo** [comment]
Hi Tim, thanks for the interest.

> I think the second one is quite hard to achieve.

For me it works well right at my working desk. But maybe we are just lucky with the lights in our office :) If yours are not so good, you can try to reduce the size of the paper to increase the chance that it is uniformly illuminated.

> I wanted to ask what you think about this way, if you've tried it, and how your results are.

Thanks for the link, interesting reading. Yes, I had an idea of using the screen to get a "ground truth" vignetting response. I tried it, but (a) I did not take care of working in complete darkness (b) instead of a close-up view, I positioned the camera at the maximum distance such that the screen was still occupying the whole image. With this setup I got unsatisfactory results (IIRC the obtained image rather showed the imperfection of the display than vignetting effects of the camera) and I abandoned the idea.

Thinking about it again, focusing on a small section of the screen to increase the chance of uniformity, as well as working in complete darkness may do the job. I'll give it a try, compare with the paper method, and let you know.

**Comment by caselitz** [comment]
Hi Sergey, thanks for your reply.

> I'll give it a try, compare with the paper method, and let you know.

awesome!

**Comment by taketwo** [comment]
So I gave it a try. Here is the setup that I used:

![scaled](https://user-images.githubusercontent.com/1241736/28706977-d0c5dd04-7376-11e7-9d30-d7035c14c3e2.png)

The screen is covered with a piece of sheet, leaving only a small hole. (Actually, two, I tried separately with both sizes.) The resulting vignetting image looks very nice, smooth, and generally reasonable. However, compared to the paper calibration, it indeed seems to be overcompensate the outer parts. Here is a short video where the camera observes a piece of paper. Top right is the original color stream, bottom right is the result of vignetting correction with the calibration from screen. Left column are the residuals computed by subtracting the mean values of a small central region of the corrected image from the complete image (in other words, it shows deviations from color uniformity in the corrected image). I think it's clear to see that the outer parts become too bright after correction.

![output](https://user-images.githubusercontent.com/1241736/28706984-d585bc4c-7376-11e7-9926-b3810649855a.gif)

I guess the screen is not Lambertian enough, so at very slanted observation angles the reflectance is lower.

**Comment by caselitz** [comment]
Thanks for your efforts!

So we both made the same observation and I think the reason

> I guess the screen is not Lambertian enough, so at very slanted observation angles the reflectance is lower.

is a very good explanation.

Again citing from [here](http://www.imatest.com/docs/uniformity_int/):

> (We prefer the LCD monitor, but this approach may work in come cases.) Photograph an evenly-lit smooth matte sheet (white or gray). Be careful not to shade it. Outdoors illumination (shade) sometimes provides very even illumination. Getting uniform illumination can be a challenge with ultrawide lenses; it’s almost impossible to avoid shading part of the card. Opal diffusing glass is strongly recommended.

So I think I'll try the two options when I find the time:
1. try to put opal diffusing glass in front of the screen (or better camera?)
2. try with a sheet in outdoor shade

**Comment by taketwo** [comment]
Okay, please drop a message if you get any interesting results!
I will close this for now.
